export const HELP_LINKS = [
  { label: "Clients", href: "/" },
  { label: "Settings", href: "/settings" },
  { label: "Account Data", href: "/settings#account-data" },
  { label: "Requests", href: "/messages" },
  { label: "Docs", href: "/docs" },
  { label: "About the App", href: "/about" },
  { label: "Public Support", href: "/support" },
  { label: "Payment Terms", href: "/terms#payment-enforcement" },
  { label: "Terms of Use", href: "/terms" },
  { label: "Privacy Policy", href: "/privacy" },
];

export const HELP_SECTIONS = [
  {
    id: "overview",
    title: "What ARK Client Center does",
    summary: "ARK Client Center gives your business one place to review receptionist activity, manage leads and clients, update account information, manage payment methods, download client data, request changes, get urgent help, and review account policies.",
    points: [
      "The Clients page is the main page after you sign in.",
      "Settings contains business details, billing controls, client-data downloads, requests, policies, and documentation.",
      "The Help button stays pinned to the screen throughout the full-access signed-in app. It can open these docs or start a quick AI help chat.",
      "The public About, Support, Terms, Privacy, and Docs pages can be reviewed without signing in.",
      "The AI help chat can explain the app and send you to the correct page. It cannot change your account, billing, clients, or requests for you.",
    ],
    links: ["Clients", "Settings", "About the App", "Public Support"],
  },
  {
    id: "stats",
    title: "Your Stats",
    summary: "Your Stats is at the top of the Clients page. Use Today, This Month, or All Time to change the reporting period.",
    points: [
      "Contacted You is a permanent activity total. Moving or deleting a person later does not remove the earlier contact from this statistic.",
      "Usage shows recorded receptionist usage. The standard service is designed around up to 1,500 included minutes per billing cycle, subject to the account’s written plan.",
      "An overage applies only after included minutes are exceeded and only when an overage rate has been disclosed for the account.",
      "Clients is a permanent total of people accepted as clients. Deleting a client later does not reduce the historical total.",
      "The numbers in Your Stats are historical records. The live Contacted Me and Clients lists below them show only the records currently in those lists.",
    ],
    links: ["Clients"],
  },
  {
    id: "pricing-minutes",
    title: "Pricing and how minutes work",
    summary: "The total service price can consist of the recurring base subscription plus a disclosed overage only when recorded usage exceeds the included minutes.",
    points: [
      "Base subscription: the recurring price shown during payment setup, in Stripe, on an invoice, or in a written plan agreement.",
      "Included usage: the standard service is designed around up to 1,500 receptionist minutes during each billing cycle, unless a different written plan applies.",
      "Usage is measured from the connected receptionist or AI/phone provider records available to ARK.",
      "No usage overage is added when recorded usage stays at or below the included amount.",
      "When an account exceeds its included minutes, only the excess usage is eligible for an additional charge.",
      "The exact overage calculation and rate must be disclosed for the account before it is assessed. Account-specific plan documents, invoices, and written agreements control over this general guide.",
      "Taxes, provider pass-through charges, custom work, or other fees apply only when separately disclosed or agreed.",
    ],
    links: ["Payment Terms", "Terms of Use"],
  },
  {
    id: "contacted-me",
    title: "Contacted Me",
    summary: "Contacted Me shows the people who are currently waiting for your review, with the oldest waiting lead shown first.",
    points: [
      "View opens the person's saved information.",
      "Delete permanently removes the person from the current Contacted Me list.",
      "Accept moves the person into Clients.",
      "Accept + Contact moves the person into Clients and also adds the available contact information to your device contacts when supported.",
      "New leads are added at the bottom so an older waiting person is not buried by newer calls.",
      "The number shown for Contacted Me is the current number of records in that list. It is different from the permanent Contacted You statistic.",
    ],
    links: ["Clients"],
  },
  {
    id: "clients",
    title: "Clients",
    summary: "Clients shows the people you have accepted and currently keep in your client list, with the newest accepted client shown first.",
    points: [
      "View opens the client's saved information.",
      "Edit lets you update the client's saved details.",
      "Contact opens the available device contact workflow when supported.",
      "Confirm Date creates a calendar item from the available appointment or job information when supported.",
      "Delete removes the client from the current list. It does not erase the historical Clients statistic.",
      "The number shown on the Clients list is the current number of saved clients, not the lifetime total.",
    ],
    links: ["Clients"],
  },
  {
    id: "business-settings",
    title: "Business Details and what ARK can see",
    summary: "Open Settings from the gear button in the upper-right corner. Business Details contains the information entered when the account was created.",
    points: [
      "You can update the business name, owner name, notification email, and notification phone while the account has full access.",
      "Press Save Settings after making changes.",
      "Authorized ARK administrators can see business and account details, Contacted Me records, accepted Client records, request history, connection status, usage records, billing status and payment incidents, policy-acceptance records, and technical information needed to operate or support the service.",
      "Client and lead records can include names, phone numbers, email addresses, addresses, requested services, appointment details, messages, and notes.",
      "ARK administrators do not receive your account password and do not receive or store full payment-card numbers. Stripe handles full card details.",
      "Access is intended for operating, supporting, securing, testing, billing, and administering the service—not for unrelated advertising or sale of customer information.",
    ],
    links: ["Settings", "Privacy Policy"],
  },
  {
    id: "billing",
    title: "Billing, missed payments, and access",
    summary: "The Payment Method section is inside Settings and opens Stripe's secure billing portal. Payment notices also provide a direct Update Payment button.",
    points: [
      "Use the billing portal to add, replace, remove, or update payment methods when Stripe allows the action.",
      "Full card details are handled by Stripe. ARK does not receive or store your full card number.",
      "After Stripe reports an unpaid scheduled payment, the system normally waits 24 hours before showing the incident or starting enforcement.",
      "Payment incidents are counted in a rolling six-month period.",
      "A first incident normally receives seven days of full-access grace after the initial 24 hours. A second incident within six months can enter restricted mode after the initial 24 hours. A third or later incident can enter manual deletion review after the initial 24 hours.",
      "Payment-restricted mode allows new leads to arrive and allows those leads to be reviewed and accepted into Clients. Settings, help requests, change requests, data exports, and other account features are unavailable.",
      "When Stripe confirms payment, full access is designed to restore automatically.",
      "Permanent deletion is not automatic. An authorized ARK administrator must review and separately confirm it.",
    ],
    links: ["Settings", "Payment Terms"],
  },
  {
    id: "request-change",
    title: "Request a Change",
    summary: "Use Request a Change on the Requests page for routine updates, improvements, questions, and non-urgent receptionist work.",
    points: [
      "Examples include changing wording, voice, speed, business information, hours, appearance, or another normal service setting.",
      "Enter a subject, explain the requested change in Details, and press Send Change Request.",
      "A new request begins as Submitted. ARK may mark it In Progress, Completed, or Denied and may include a message explaining the decision or result.",
      "Closed requests remain in your account history but leave the administrator's active work queue.",
      "Requests are unavailable while the account is payment-restricted.",
    ],
    links: ["Requests"],
  },
  {
    id: "priority-help",
    title: "Priority Help",
    summary: "Priority Help is available on the Requests page for serious problems that are currently affecting the business.",
    points: [
      "Examples include the business number not answering, the receptionist not working, missing lead data, or another major service failure.",
      "Enter what is broken as the subject, explain what is happening, and press Send Priority Help.",
      "ARK treats genuine priority problems as urgent.",
      "Routine changes sent as Priority Help may be denied, handled as a normal request, or returned with instructions to resubmit through Request a Change.",
      "Priority Help is unavailable while the account is payment-restricted; use the payment controls to restore access.",
      "The public Support page remains available for login trouble, privacy questions, and general App Store support.",
    ],
    links: ["Requests", "Public Support"],
  },
  {
    id: "terms-privacy",
    title: "Terms of Use and Privacy Policy",
    summary: "Settings and the public website provide links to the current Terms of Use and Privacy Policy. Payment notices include a Learn More link to the payment-enforcement terms.",
    points: [
      "The Terms explain recurring billing, included services, usage charges, payment enforcement, cancellation, account restrictions, exports, manual deletion review, and permanent deletion.",
      "The Privacy Policy explains exactly what information ARK can see, why it is used, which providers may process it, and how restriction, retention, export, and deletion work.",
      "Permanent account deletion removes the active business account and its active Contacted Me and Clients records. Limited billing, security, agreement, audit, backup, or legal records may remain where required or permitted.",
      "The version and effective date are shown on each policy page.",
      "ARK may require renewed acceptance after a material policy update. When renewed acceptance is required, access may be limited until the current policies are accepted.",
    ],
    links: ["Terms of Use", "Privacy Policy"],
  },
  {
    id: "data-account",
    title: "Data downloads, cancellation, and account deletion",
    summary: "Settings includes a direct Download Client Data button. Cancellation and deletion requests can be sent through Requests while the account has full access.",
    points: [
      "Download Client Data creates a JSON file containing current Contacted Me records, accepted Clients, account details, and request history.",
      "Keep downloaded files secure because they can contain customer personal information.",
      "Request an export before deletion and while required service charges are paid. Downloads may be unavailable while the account is payment-restricted.",
      "Use Request a Change for a normal cancellation or deletion request. Use Priority Help for a serious security or immediate account-access problem.",
      "A normal cancellation generally keeps service available through the current paid billing period and stops it before the next renewal, unless a different written agreement applies.",
      "Permanent deletion requires administrator confirmation and deletes the active account together with its active Contacted Me and Clients data. Deleted active data may not be recoverable or available for export.",
      "Limited billing, security, backup, agreement, audit, fraud-prevention, or legal records may be retained where required or permitted.",
    ],
    links: ["Account Data", "Requests", "Payment Terms", "Terms of Use", "Privacy Policy"],
  },
  {
    id: "where-things-are",
    title: "Where to find everything",
    summary: "Use this quick map when you know what you need but not where it is.",
    points: [
      "Stats: top of the Clients page while the account has full access.",
      "Contacted Me and Clients: main Clients page below Your Stats.",
      "Business details and Save Settings: Settings.",
      "Download Client Data: Settings, then Account Data.",
      "Payment methods: Settings, then Payment Method, or Update Payment in an account notice.",
      "Routine changes: Requests, then Request a Change.",
      "Serious service problems: Requests, then Priority Help.",
      "Public app information and contact: About the App and Public Support.",
      "Terms, Privacy, and Docs: Settings, the login/signup pages, or the public website.",
      "AI assistance: press the pinned Help button on any full-access signed-in page, then Ask AI for Help.",
    ],
    links: ["Clients", "Settings", "Account Data", "Requests", "About the App", "Public Support", "Payment Terms", "Terms of Use", "Privacy Policy"],
  },
];

export const HELP_KNOWLEDGE = HELP_SECTIONS.map((section) => {
  const points = section.points.map((point) => `- ${point}`).join("\n");
  const links = section.links.join(", ");
  return `## ${section.title}\n${section.summary}\n${points}\nRelevant page links: ${links}`;
}).join("\n\n");
