export const HELP_LINKS = [
  { label: "Dashboard", href: "/" },
  { label: "Settings", href: "/settings" },
  { label: "Help", href: "/help" },
  { label: "Send a Message", href: "/messages" },
  { label: "Account Data", href: "/settings#account-data" },
  { label: "Docs", href: "/docs" },
  { label: "About the App", href: "/about" },
  { label: "Public Support", href: "/support" },
  { label: "Payment Terms", href: "/terms#paid-service" },
  { label: "Payment Enforcement", href: "/terms#payment-enforcement" },
  { label: "Terms of Use", href: "/terms" },
  { label: "Privacy Policy", href: "/privacy" },
];

export const HELP_SECTIONS = [
  {
    id: "overview",
    title: "What ARK Client Center does",
    summary: "ARK Client Center gives your business one place to review receptionist activity, manage leads and clients, view completed-call usage and the current amount due, choose a future plan, update business information, manage payment methods, download data, and request help.",
    points: [
      "The Dashboard is the main page after you sign in or reopen the app.",
      "The billing card shows the current receptionist plan, calls used, calls remaining, overage, and estimated amount due.",
      "Settings contains the collapsible AI receptionist and business-information editor, payment controls, data downloads, Help, policies, and documentation.",
      "Help is available only from Settings. It provides Go to Docs, Ask AI, and Send a Message.",
      "The public About, Support, Terms, Privacy, and Docs pages can be reviewed without signing in.",
      "Ask AI can explain the app and provide links. It cannot change billing, account data, leads, clients, or settings.",
    ],
    links: ["Dashboard", "Settings", "Help", "About the App"],
  },
  {
    id: "dashboard-billing",
    title: "Calls and amount due this month",
    summary: "The Dashboard shows the current plan, completed-call allowance, overage, and estimated amount due for the month.",
    points: [
      "Every new account normally begins with Starter 25 at $49 per month, including 25 completed calls.",
      "The Dashboard counts down the number of included calls remaining before overage begins.",
      "After the allowance is used, the Dashboard shows the number of overage calls and their current dollar amount.",
      "The amount due is the current monthly plan price plus completed-call overage.",
      "Recent usage can take time to reach Stripe, and Stripe's finalized invoice controls the final charged amount.",
    ],
    links: ["Dashboard", "Payment Terms", "Terms of Use"],
  },
  {
    id: "pricing",
    title: "Plans, overage, and recommendations",
    summary: "Plans trade a lower monthly price and smaller call allowance for a higher overage rate, or a higher monthly price and larger allowance for a lower overage rate.",
    points: [
      "Starter 25 is the minimum plan: $49 monthly, 25 included completed calls, then $1.50 per additional completed call.",
      "Higher plans include more calls and reduce the overage price per completed call.",
      "After the first full month, ARK uses the previous month's completed-call total to show three choices: lower monthly, recommended, and more included calls or lower overage.",
      "Selecting a plan schedules it for the next calendar billing month. The current plan remains locked for the current month.",
      "Changing a future plan does not remove calls or overage already recorded.",
      "Usage above 1,000 completed calls may qualify for custom high-volume pricing.",
    ],
    links: ["Dashboard", "Payment Terms", "Terms of Use"],
  },
  {
    id: "completed-calls",
    title: "What counts as a completed call",
    summary: "A completed call is normally a legitimate AI receptionist call lasting at least 20 seconds.",
    points: [
      "A legitimate call can count whether or not the caller ultimately becomes a lead or client.",
      "Known test calls, immediate hang-ups, failed or rejected calls, and calls caused by a documented system error do not use the included-call allowance.",
      "Duplicate usage records are blocked using the call identifier.",
      "Contact ARK through Help if you believe a call was classified incorrectly.",
    ],
    links: ["Dashboard", "Help", "Payment Terms"],
  },
  {
    id: "contacted-me",
    title: "Contacted Me",
    summary: "Contacted Me shows the people who are currently waiting for your review.",
    points: [
      "Call billing is based on completed receptionist calls, not on moving or deleting a lead record.",
      "View opens the person's saved information.",
      "Delete permanently removes the person from the current Contacted Me list but does not change a completed call already recorded.",
      "Accept moves the person into Clients.",
      "Accept + Contact moves the person into Clients and opens the available device contact workflow.",
      "The Contacted You statistic preserves historical activity even after a current record is moved or deleted.",
    ],
    links: ["Dashboard"],
  },
  {
    id: "clients",
    title: "Clients",
    summary: "Clients shows the people the business has accepted and currently keeps in its client list.",
    points: [
      "View opens the client's saved information.",
      "Edit updates the saved client details.",
      "Contact opens the device contact workflow when supported.",
      "Confirm Date opens the calendar workflow when supported.",
      "Deleting a client removes the current record but does not change earlier completed-call usage or historical statistics.",
    ],
    links: ["Dashboard"],
  },
  {
    id: "business-settings",
    title: "Business Information and AI settings",
    summary: "Open Settings and press View and edit on Business Information.",
    points: [
      "The section is collapsed until View and edit is pressed, except during required first-time business setup.",
      "It contains the receptionist voice and timing, business name, receptionist name, owner, phone, email, time zone, business days and hours, estimate availability, service areas, business facts, and services.",
      "The ARK administrator sees the same saved information and also has the private connected phone-number control.",
      "Stripe handles full payment-card details. ARK stores only billing identifiers and a safe payment-method label, not the full card number.",
    ],
    links: ["Settings", "Privacy Policy"],
  },
  {
    id: "help",
    title: "Help",
    summary: "Help is available only in Settings so the rest of the app stays uncluttered.",
    points: [
      "Go to Docs opens this full app guide.",
      "Ask AI answers questions about using the app and can provide page links.",
      "Send a Message contacts ARK about technical problems, billing questions, call-classification disputes, service issues, cancellation, deletion, or other account needs.",
      "The AI chat clears 24 hours after the most recent message.",
      "Signed-in Help messages may be unavailable during payment restriction. Public Support remains available for login and general access issues.",
    ],
    links: ["Help", "Send a Message", "Public Support"],
  },
  {
    id: "billing-access",
    title: "Billing, payment methods, missed payments, and access",
    summary: "Settings opens Stripe's secure billing portal, while the Dashboard shows the current plan, call usage, overage, and amount due.",
    points: [
      "Use Manage Payment Method in Settings to update the payment method through Stripe.",
      "Stripe processes the monthly plan subscription and metered completed-call overage.",
      "After Stripe reports an unpaid scheduled payment, the system normally waits 24 hours before beginning the documented enforcement process.",
      "Payment-restricted mode can allow incoming leads and lead review while disabling Settings, Help messages, downloads, and other features.",
      "When Stripe confirms payment, full access is designed to restore automatically.",
      "Permanent deletion is a separate administrator decision and is not automatic merely because a deadline passes.",
    ],
    links: ["Settings", "Payment Enforcement", "Terms of Use"],
  },
  {
    id: "data-legal",
    title: "Downloads, policies, cancellation, and deletion",
    summary: "Settings includes data download and direct links to Terms, Privacy, Docs, and Help.",
    points: [
      "Download Client Data asks you where to save the JSON file and does not grant the app ongoing access to your files.",
      "Keep downloaded files secure because they can contain customer personal information.",
      "Use Settings, Help, and Send a Message for cancellation or account-deletion requests.",
      "Permanent deletion requires administrator confirmation and removes the active account together with active Contacted Me and Clients records.",
      "Cancellation does not reverse completed-call overage already incurred during the current billing period.",
      "The Terms explain plans, completed calls, overage, recommendations, payment enforcement, cancellation, exports, and deletion.",
      "The Privacy Policy explains what information ARK and its providers process and why.",
    ],
    links: ["Account Data", "Help", "Terms of Use", "Privacy Policy"],
  },
  {
    id: "where-things-are",
    title: "Where to find everything",
    summary: "Use this quick map when you know what you need but not where it is.",
    points: [
      "Current plan, calls remaining, overage, amount due, recommendations, and stats: Dashboard.",
      "Contacted Me and Clients: Dashboard below the stats area.",
      "Business Information and AI settings: Settings, then View and edit.",
      "Payment method: Settings, then Payment Method.",
      "Download Client Data: Settings.",
      "Docs, Ask AI, and Send a Message: Settings, then Help.",
      "Terms, Privacy, and Docs links: Settings.",
    ],
    links: ["Dashboard", "Settings", "Help", "Terms of Use", "Privacy Policy"],
  },
];

export const HELP_KNOWLEDGE = HELP_SECTIONS.map((section) => {
  const points = section.points.map((point) => `- ${point}`).join("\n");
  const links = section.links.join(", ");
  return `## ${section.title}\n${section.summary}\n${points}\nRelevant page links: ${links}`;
}).join("\n\n");
