// swift-tools-version: 5.9
import PackageDescription

// This file is generated by scripts/configure-ios.mjs.
// Native plugin source is checked into the repository so Xcode can build a fresh clone
// without requiring Node, npm, or a node_modules directory on the Mac.
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "CapApp-SPM", targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", exact: "8.4.2")
    ],
    targets: [
        .target(
            name: "PushNotificationsPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "Sources/PushNotificationsPlugin"
        ),
        .target(
            name: "ContactsPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "Sources/ContactsPlugin"
        ),
        .target(
            name: "CapacitorCalendarPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "Sources/CapacitorCalendarPlugin"
        ),
        .target(
            name: "CapApp-SPM",
            dependencies: [
                "PushNotificationsPlugin",
                "ContactsPlugin",
                "CapacitorCalendarPlugin"
            ],
            path: "Sources/CapAppSPM"
        )
    ]
)
