import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, "..");
const iosRoot = path.join(projectRoot, "ios", "App");
const appRoot = path.join(iosRoot, "App");
const plistPath = path.join(appRoot, "Info.plist");
const appDelegatePath = path.join(appRoot, "AppDelegate.swift");
const swiftPackageRoot = path.join(iosRoot, "CapApp-SPM");
const swiftSourcesRoot = path.join(swiftPackageRoot, "Sources");

function requireFile(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Required iOS file was not generated: ${path.relative(projectRoot, filePath)}`);
  }
}

function requireDirectory(directoryPath) {
  if (!fs.existsSync(directoryPath) || !fs.statSync(directoryPath).isDirectory()) {
    throw new Error(`Required iOS plugin source was not installed: ${path.relative(projectRoot, directoryPath)}`);
  }
}

function copyDirectory(source, destination) {
  requireDirectory(source);
  fs.rmSync(destination, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.cpSync(source, destination, { recursive: true });
}

function escapeXml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function addPlistString(plist, key, value) {
  if (plist.includes(`<key>${key}</key>`)) return plist;
  const addition = `\n\t<key>${key}</key>\n\t<string>${escapeXml(value)}</string>`;
  const closing = "\n</dict>\n</plist>";
  if (!plist.includes(closing)) throw new Error("Info.plist has an unexpected format.");
  return plist.replace(closing, `${addition}${closing}`);
}

function vendorNativePluginSources() {
  const pluginSources = [
    {
      source: path.join(projectRoot, "node_modules", "@capacitor", "push-notifications", "ios", "Sources", "PushNotificationsPlugin"),
      destination: path.join(swiftSourcesRoot, "PushNotificationsPlugin"),
    },
    {
      source: path.join(projectRoot, "node_modules", "@capacitor-community", "contacts", "ios", "Sources", "ContactsPlugin"),
      destination: path.join(swiftSourcesRoot, "ContactsPlugin"),
    },
    {
      source: path.join(projectRoot, "node_modules", "@ebarooni", "capacitor-calendar", "ios", "Plugin"),
      destination: path.join(swiftSourcesRoot, "CapacitorCalendarPlugin"),
    },
  ];

  fs.rmSync(swiftSourcesRoot, { recursive: true, force: true });
  fs.mkdirSync(swiftSourcesRoot, { recursive: true });
  for (const plugin of pluginSources) copyDirectory(plugin.source, plugin.destination);

  const wrapperSource = path.join(swiftSourcesRoot, "CapAppSPM", "CapAppSPM.swift");
  fs.mkdirSync(path.dirname(wrapperSource), { recursive: true });
  fs.writeFileSync(wrapperSource, "// Native Capacitor plugins are linked through this self-contained Swift package.\n");

  const packageManifest = `// swift-tools-version: 5.9
import PackageDescription

// This file is generated by scripts/configure-ios.mjs.
// Native plugin source is checked into the repository so Xcode can build a fresh clone
// without requiring Node, npm, or a node_modules directory on the Mac.
let package = Package(
    name: "CapApp-SPM",
    platforms: [.iOS(.v15)],
    products: [
        .library(name: "CapApp-SPM", targets: ["CapApp-SPM"])
    ],
    dependencies: [
        .package(url: "https://github.com/ionic-team/capacitor-swift-pm.git", exact: "8.4.2")
    ],
    targets: [
        .target(
            name: "PushNotificationsPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "Sources/PushNotificationsPlugin"
        ),
        .target(
            name: "ContactsPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "Sources/ContactsPlugin"
        ),
        .target(
            name: "CapacitorCalendarPlugin",
            dependencies: [
                .product(name: "Capacitor", package: "capacitor-swift-pm"),
                .product(name: "Cordova", package: "capacitor-swift-pm")
            ],
            path: "Sources/CapacitorCalendarPlugin"
        ),
        .target(
            name: "CapApp-SPM",
            dependencies: [
                "PushNotificationsPlugin",
                "ContactsPlugin",
                "CapacitorCalendarPlugin"
            ],
            path: "Sources/CapAppSPM"
        )
    ]
)
`;

  fs.writeFileSync(path.join(swiftPackageRoot, "Package.swift"), packageManifest);
}

requireFile(plistPath);
requireFile(appDelegatePath);

let plist = fs.readFileSync(plistPath, "utf8");
plist = addPlistString(
  plist,
  "NSContactsUsageDescription",
  "ARK Client Center uses contacts only when you choose to add or match a customer contact.",
);
plist = addPlistString(
  plist,
  "NSCalendarsUsageDescription",
  "ARK Client Center uses your calendar to manage customer appointments you choose to add.",
);
plist = addPlistString(
  plist,
  "NSCalendarsWriteOnlyAccessUsageDescription",
  "ARK Client Center can add customer appointments to your calendar when you choose.",
);
plist = addPlistString(
  plist,
  "NSCalendarsFullAccessUsageDescription",
  "ARK Client Center can read and manage customer appointments in your calendar when you choose.",
);
fs.writeFileSync(plistPath, plist);

let appDelegate = fs.readFileSync(appDelegatePath, "utf8");
if (!appDelegate.includes("capacitorDidRegisterForRemoteNotifications")) {
  const closingBrace = appDelegate.lastIndexOf("\n}");
  if (closingBrace === -1) throw new Error("AppDelegate.swift has an unexpected format.");

  const pushCallbacks = `

    func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        NotificationCenter.default.post(name: .capacitorDidRegisterForRemoteNotifications, object: deviceToken)
    }

    func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(name: .capacitorDidFailToRegisterForRemoteNotifications, object: error)
    }
`;

  appDelegate = `${appDelegate.slice(0, closingBrace)}${pushCallbacks}${appDelegate.slice(closingBrace)}`;
  fs.writeFileSync(appDelegatePath, appDelegate);
}

vendorNativePluginSources();

const plistCheck = spawnSync("/usr/bin/plutil", ["-lint", plistPath], { encoding: "utf8" });
if (plistCheck.status !== 0) {
  throw new Error(plistCheck.stderr || plistCheck.stdout || "Info.plist validation failed.");
}

console.log("Configured a self-contained iOS project with contacts, calendar, and push-notification support.");
